version: '3'

services:
  backend:
    build: .
    image: cbook/backend:v0.0.1
    ports:
      - "8887:8887"
    volumes:
      - .:/usr/src/backend
    command: nodemon
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.4.4
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./datadir:/data/db
    command: ["mongod", "--auth"]
    ports: 
      - '27017:27017'